server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    
    include /etc/nginx/mime.types;
    types {
        application/javascript mjs;
    }

    location / {
        try_files $uri /index.html;
    }

    # Bütün mjs, js ve css dosyaları için özel lokasyon, hata yapmasını önlemek için.
    location ~ \.(mjs|js|css)$ {
        try_files $uri =404;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }
}