server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    
    include /etc/nginx/mime.types;
    types {
        application/javascript mjs;
    }

    location / {
        try_files $uri /index.html;
    }

    # Proxy API requests to the backend container
    location /api/ {
        proxy_pass http://backend:5000/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Bütün mjs, js ve css dosyaları için özel lokasyon, hata yapmasını önlemek için.
    location ~ \.(mjs|js|css)$ {
        try_files $uri =404;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }
}